server:
  port: 7543

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Employee_db
    username: root
    password: Pranjali@#115
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

logging:
  file:
    name: employee-app.log
  level:
    root: INFO
    com.example.EmployeeManagementSystem: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always


